name: payne_optuna
channels:
  - defaults
dependencies:
  - python=3.8.*
  - ipython>=7.20
  - setuptools>=52.0
  - pyyaml>=5.4
  - numpy>=1.19
  - pandas>=1.2
  - scipy>=1.6
  - astropy>=4.2
  - pytables>=3.6
  - notebook>=6.2
  - matplotlib>=3.3
  - cudatoolkit=10.2.*
  - pytorch::pytorch>=1.7
  - pytorch::torchaudio>=0.7
  - pytorch::torchvision>=0.8
  - conda-forge::pytorch-lightning==1.2.6
  - conda-forge::optuna>=2.5
  - conda-forge::tensorboard>=2.4
  - conda-forge::ipywidgets>=7.5
  - plotly::plotly>=4.14